const mockMovies = [ 
  { Year: '1990',
  Length: '111',
  Title: 'Tie Me Up! Tie Me Down!',
  Subject: 'Comedy',
  Actor: 'Banderas, Antonio',
  Actress: 'Abril, Victoria',
  Director: 'Almodóvar, Pedro',
  Popularity: '68',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1991',
  Length: '113',
  Title: 'High Heels',
  Subject: 'Comedy',
  Actor: 'Bosé, Miguel',
  Actress: 'Abril, Victoria',
  Director: 'Almodóvar, Pedro',
  Popularity: '68',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1983',
  Length: '104',
  Title: 'Dead Zone, The',
  Subject: 'Horror',
  Actor: 'Walken, Christopher',
  Actress: 'Adams, Brooke',
  Director: 'Cronenberg, David',
  Popularity: '79',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1979',
  Length: '122',
  Title: 'Cuba',
  Subject: 'Action',
  Actor: 'Connery, Sean',
  Actress: 'Adams, Brooke',
  Director: 'Lester, Richard',
  Popularity: '6',
  Awards: 'No',
  '*Image': 'seanConnery.png' },
  { Year: '1978',
  Length: '94',
  Title: 'Days of Heaven',
  Subject: 'Drama',
  Actor: 'Gere, Richard',
  Actress: 'Adams, Brooke',
  Director: 'Malick, Terrence',
  Popularity: '14',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1983',
  Length: '140',
  Title: 'Octopussy',
  Subject: 'Action',
  Actor: 'Moore, Roger',
  Actress: 'Adams, Maud',
  Director: 'Glen, John',
  Popularity: '68',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1984',
  Length: '101',
  Title: 'Target Eagle',
  Subject: 'Action',
  Actor: 'Connors, Chuck',
  Actress: 'Adams, Maud',
  Director: 'Loma, José Antonio de la',
  Popularity: '14',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1989',
  Length: '99',
  Title: 'American Angels: Baptism of Blood, The',
  Subject: 'Drama',
  Actor: 'Bergen, Robert D.',
  Actress: 'Adams, Trudy',
  Director: 'Sebastian, Beverly',
  Popularity: '28',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1985',
  Length: '104',
  Title: 'Subway',
  Subject: 'Drama',
  Actor: 'Lambert, Christopher',
  Actress: 'Adjani, Isabelle',
  Director: 'Besson, Luc',
  Popularity: '6',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1990',
  Length: '149',
  Title: 'Camille Claudel',
  Subject: 'Drama',
  Actor: 'Depardieu, Gérard',
  Actress: 'Adjani, Isabelle',
  Director: 'Nuytten, Bruno',
  Popularity: '32',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1982',
  Length: '188',
  Title: 'Fanny and Alexander',
  Subject: 'Drama',
  Actor: 'Ahlstedt, Börje',
  Actress: 'Adolphson, Kristina',
  Director: 'Bergman, Ingmar',
  Popularity: '81',
  Awards: 'Yes',
  '*Image': 'Bergman.png' },
  { Year: '1982',
  Length: '117',
  Title: 'Tragedy of a Ridiculous Man',
  Subject: 'Drama',
  Actor: 'Tognazzi, Ugo',
  Actress: 'Aimee, Anouk',
  Director: 'Bertolucci, Bernardo',
  Popularity: '17',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1966',
  Length: '103',
  Title: 'A Man & a Woman',
  Subject: 'Drama',
  Actor: 'Trintignant, Jean-Louis',
  Actress: 'Aimee, Anouk',
  Director: 'Lelouch, Claude',
  Popularity: '46',
  Awards: 'Yes',
  '*Image': 'NicholasCage.png' },
  { Year: '1986',
  Length: '112',
  Title: 'A Man & a Woman: Twenty Years Later',
  Subject: 'Drama',
  Actor: 'Trintignant, Jean-Louis',
  Actress: 'Aimee, Anouk',
  Director: 'Lelouch, Claude',
  Popularity: '49',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1966',
  Length: '103',
  Title: 'Un Hombre y una Mujer',
  Subject: 'Drama',
  Actor: 'Trintignant, Jean-Louis',
  Actress: 'Aimee, Anouk',
  Director: 'Lelouch, Claude',
  Popularity: '6',
  Awards: 'Yes',
  '*Image': 'NicholasCage.png' },
  { Year: '1985',
  Length: '112',
  Title: 'Official Story, The',
  Subject: 'Drama',
  Actor: 'Alterio, Hector',
  Actress: 'Aleandro, Norma',
  Director: 'Puenzo, Luiz',
  Popularity: '39',
  Awards: 'Yes',
  '*Image': 'NicholasCage.png' },
  { Year: '1976',
  Length: '150',
  Title: 'Lindbergh Kidnapping Case, The',
  Subject: 'Drama',
  Actor: 'Hopkins, Anthony',
  Actress: 'Alexander, Denise',
  Director: 'Kulik, Buzz',
  Popularity: '51',
  Awards: 'No',
  '*Image': 'AnthonyHopkins.png' },
  { Year: '1929',
  Length: '84',
  Title: 'Blackmail',
  Subject: 'Mystery',
  Actor: 'Longden, John',
  Actress: 'Algood, Sara',
  Director: 'Hitchcock, Alfred',
  Popularity: '2',
  Awards: 'No',
  '*Image': 'alfredHitchcock.png' },
  { Year: '1963',
  Length: '109',
  Title: 'Donovan\'s Reef',
  Subject: 'Comedy',
  Actor: 'Wayne, John',
  Actress: 'Allen, Elizabeth',
  Director: 'Ford, John',
  Popularity: '62',
  Awards: 'No',
  '*Image': 'johnWayne.png' },
  { Year: '1988',
  Length: '110',
  Title: 'Tucker: The Man & His Dream',
  Subject: 'Drama',
  Actor: 'Bridges, Jeff',
  Actress: 'Allen, Joan',
  Director: 'Coppola, Francis Ford',
  Popularity: '68',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1988',
  Length: '101',
  Title: 'Scrooged',
  Subject: 'Comedy',
  Actor: 'Murray, Bill',
  Actress: 'Allen, Karen',
  Director: 'Donner, Richard',
  Popularity: '15',
  Awards: 'No',
  '*Image': 'NicholasCage.png' },
  { Year: '1981',
  Length: '116',
  Title: 'Raiders of the Lost Ark',
  Subject: 'Action',
  Actor: 'Ford, Harrison',
  Actress: 'Allen, Karen',
  Director: 'Spielberg, Steven',
  Popularity: '8',
  Awards: 'No',
  '*Image': 'NicholasCage.png' }
]

exports.seed = function(knex) {
  return knex('movies').del()
    .then(() => knex('directors').del())
    .then(() => {
      return Promise.all([
        knex('directors').insert([

        ])
      ])
    })
};
